version: "3.7"
volumes:
  pgdata:
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 1121
    expose:
      - 1121
    env_file:
      - .env-non-dev
    restart: always
    volumes:
      - /home/dayless/IT/progs/python_code/bots/watchbot/postgres_data:/var/lib/postgresql/data
  bot:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: bot
    command: ["/bot/app.sh"]
    ports:
      - 9998:8000
    depends_on:
      - db
    restart: always
  fastapi_app:
    build:
      context: ./fastapi
    env_file: 
      - .env-non-dev
    container_name: app
    command: ["/app/fast.sh"]
    ports:
      - 9000:8000
    depends_on:
      - db
      - bot
    restart: always
