version: "3.7"
volumes:
  pgdata:
  fastapidata:
services:
  bot_db:
    image: postgres:15
    container_name: bot_db
    ports:
      - 1121:5432
    env_file:
      - .env-non-dev
    restart: always
    networks:
      - network1
    volumes:
      - pgdata:/var/lib/postgresql/data
  bot:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: bot
    command: ["/bot/app.sh"]
    ports:
      - 9998:8000
    depends_on:
      - bot_db
    networks:
      - network1
    restart: always
  fastapi_app:
    build:
      context: ./fastapi
    env_file: 
      - .env-non-dev
    container_name: fastapi_app
    command: ["/app/fast.sh"]
    ports:
      - 9000:8000
    depends_on:
      - bot_db
      - bot
    networks:
      - network1
    volumes:
      - fastapidata:/app
    restart: always
networks:
  network1:
    name: watch-blockchain_default
    external: true
