"""empty message

Revision ID: 98dbc5af7783
Revises: ab0000c49cbe
Create Date: 2023-12-26 11:26:06.795754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98dbc5af7783'
down_revision = 'ab0000c49cbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('booking', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'booking')
    # ### end Alembic commands ###
