"""empty message

Revision ID: 22ed12d869c2
Revises: 704fb9bdc565
Create Date: 2023-12-28 03:23:39.212551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ed12d869c2'
down_revision = '704fb9bdc565'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'user_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user_message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
