"""empty message

Revision ID: 13454494e82f
Revises: 
Create Date: 2024-01-11 01:12:20.877865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13454494e82f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('watch',
    sa.Column('watch_id', sa.Integer(), nullable=False),
    sa.Column('channel_message_id', sa.Integer(), nullable=True),
    sa.Column('admin_message_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('watch_name', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('watch_registred_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('watch_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('watch_id', sa.Integer(), nullable=False),
    sa.Column('book_or_buy', sa.String(), nullable=True),
    sa.Column('order_price', sa.Double(), nullable=True),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('order_registred_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['tg_id'], ['user.tg_id'], ),
    sa.ForeignKeyConstraint(['watch_id'], ['watch.watch_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('watch_id', sa.Integer(), nullable=False),
    sa.Column('transaction_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['watch_id'], ['watch.watch_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('order')
    op.drop_table('watch')
    op.drop_table('user')
    # ### end Alembic commands ###
