"""empty message

Revision ID: 022701a96d9c
Revises: bb6366aa1726
Create Date: 2024-01-06 17:20:28.574146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022701a96d9c'
down_revision = 'bb6366aa1726'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
