"""empty message

Revision ID: 1d3b48e281c5
Revises: 
Create Date: 2024-03-13 01:14:38.070535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3b48e281c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('watch',
    sa.Column('watch_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_message_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_message_id', sa.BigInteger(), nullable=True),
    sa.Column('unique_file_id', sa.String(), nullable=True),
    sa.Column('msg_txt', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('booking_price', sa.Integer(), nullable=False),
    sa.Column('watch_name', sa.String(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('watch_registred_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('watch_id'),
    sa.UniqueConstraint('unique_file_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('watch_id', sa.BigInteger(), nullable=False),
    sa.Column('book_or_buy', sa.String(), nullable=True),
    sa.Column('order_price', sa.Double(), nullable=True),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('order_registred_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['tg_id'], ['user.tg_id'], ),
    sa.ForeignKeyConstraint(['watch_id'], ['watch.watch_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('watch_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_data', sa.JSON(), nullable=False),
    sa.Column('transaction_time', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['watch_id'], ['watch.watch_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('watch_file',
    sa.Column('watch_file_id', sa.BigInteger(), nullable=False),
    sa.Column('unique_file_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('watch_file_registred_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('watch_file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watch_file')
    op.drop_table('transaction')
    op.drop_table('order')
    op.drop_table('watch')
    op.drop_table('user')
    # ### end Alembic commands ###
